export const actionType ={
    SET_USERLIST:"SET_USERLIST",
    SET_ADMIN:"SET_ADMIN",
    SET_ADMIN_PROFILE:"SET_ADMIN_PROFILE",
    SET_SELECTED_USER:"SET_SELECTED_USER",
    SET_MOVIELIST:"SET_MOVIELIST",
    SET_SELECTED_MOVIE:"SET_SELECTED_MOVIE",
    SET_MOVIE_DETAIL:"SET_MOVIE_DETAIL",
    SET_THEATER_SYSTEM_INFOR:"SET_THEATER_SYSTEM_INFOR",
    SET_THEATER_BY_SYSTEM:"SET_THEATER_BY_SYSTEM",
};